name: Build and upload docker image
on: [ push ]
jobs:
  docker-build-upload:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Retrieve current git tag
        run: echo "GIT_TAG=$(shell git describe --tags --always)" >> $GITHUB_ENV
      - name: Build docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64/v8 -f "./Dockerfile" --push \
            -t ghcr.io/${GITHUB_REPOSITORY}:${GIT_TAG} -t ghcr.io/${GITHUB_REPOSITORY}:latest \
            .
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
        if: ${{ github.ref_type == 'tag' }}
      - name: Build and push cross-platform images
        run: |
          make docker-cross-platform-buildx-push
        if: ${{ github.ref_type == 'tag' }}
